apiVersion: v1
kind: Service
metadata:
  name: firstnext-app-service
spec:
  type: NodePort
  selector:
    app: firstnext-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001

#kubectl apply -f deployment.yaml
#kubectl apply -f service.yaml 